blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Robotic-Decision-Making-Lab/hydrodynamics/discussions
    about: Please check out our discussions channel for any questions related to the project!
